#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "${SCRIPT_DIR}"/../lib/common.sh

PROJECT_DIR="$(realpath "$SCRIPT_DIR/../..")"
DOT_CONFIG="$PROJECT_DIR/.config"
CONFIG_SH_OUT="$PROJECT_DIR/scripts/lib/generated/config.sh"
CONFIG_H_OUT="$PROJECT_DIR/build/config.h"

# Normally, this shouldn't be triggered due to the build flow,
# but if this is ran on it's own and we don't have a valid dotconfig,
# show an error about it instead of failing silently.
[[ ! -f "$DOT_CONFIG" ]] && error ".config not found. Run 'make config' or 'make menuconfig' first."

mkdir -p "$(dirname "$CONFIG_SH_OUT")"
mkdir -p "$(dirname "$CONFIG_H_OUT")"

{
  echo "# Auto-generated from .config, do not edit directly"
  echo "# Generated by gen-config.sh"
  echo ""

  while IFS= read -r line; do
    if [[ "$line" =~ ^#[[:space:]]CONFIG_([A-Za-z0-9_]+)[[:space:]]is[[:space:]]not[[:space:]]set ]]; then
      varname="${BASH_REMATCH[1]}"
      echo "CONFIG_${varname}=n"
      continue
    fi

    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${line// }" ]] && continue

    if [[ "$line" =~ ^CONFIG_[A-Za-z0-9_]+=.* ]]; then
      echo "$line"
    fi
  done < "$DOT_CONFIG"
} > "$CONFIG_SH_OUT"

log "GEN" "$CONFIG_SH_OUT"